# Generated by Django 4.0.5 on 2022-08-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoPlopApp', '0002_evento_detalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagenes', models.ImageField(upload_to='eventos/')),
            ],
            options={
                'verbose_name': 'Probando',
                'verbose_name_plural': 'Probandos',
            },
        ),
    ]
