# Generated by Django 4.0.5 on 2022-08-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoPlopApp', '0003_probando'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='eventos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Probando',
        ),
    ]
