# Generated by Django 4.0.5 on 2022-08-01 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoPlopApp', '0004_multiple_delete_probando'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='eventos/')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoPlopApp.evento')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.DeleteModel(
            name='Multiple',
        ),
    ]
