# Generated by Django 4.0.5 on 2022-08-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoPlopApp', '0006_fondopagina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['fecha'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
    ]
